# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hrYppXaggTPlR4I5MqaG0thwA37fYCXg
"""

# Nomor 1
# masukan nilai n
n = int (input("masukkan nilai n="))
#inisialisasi total dan i
total = 0
i = 1
#looping untuk menghitunng jumlah
while i in range(1, n+1):
    total += 1
    i += 1

# Nomor 2
import math
#masukkan jari-jari(r)
r= float (input("Masukkan nilai jari-jari Lingkaran"))
#menghitung lingkaran
luas_lingkaran = 3,14*r**2
print("Luas Lingkaran dengan nilai jari-jari", r, "adalah", luas_lingkaran)

# Nomor 3
i = 1
i <= 5 ?
jika Ya = Letak i, tingkatkan i sebesar 1 (i+1), kembali ke langkah 2
jika Tidak = Selesai
# Kode Python mencetak angka 1-5
for i in range (1,6)
print(i, end=" ")

# Nomor 4
i = 1
1 <= 10 ?
apakah i  ganjil ?
jika Ya = cetak i
tingkatkan i sebesar 1 (i+1), kembali ke langkah 2
jika Tidak = Selesai
#kode python mencetak angka ganjil dari 1-10
print ("angka ganjil dari 1-10")
for i in range (1,11):
    if i % 2 != 0:
        print(i, end=" ")